src/Entity/Favoritos.php
<?php

namespace App\Entity;

use App\Repository\FavoritosRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FavoritosRepository::class)]
class Favoritos
{
       /*   ATRIBUTOS */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_favoritos = null;

    #[ORM\Column]
    private ?int $id_user = null;

    #[ORM\Column]
    private ?int $id_producto = null;

        /*     RELACIONES      */

        /*     METODOS      */
    
    public function getIdFavoritos(): ?int
    {
        return $this->id_favoritos;
    }

    public function setIdFavoritos(int $id_favoritos): static
    {
        $this->id_favoritos = $id_favoritos;

        return $this;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getIdProducto(): ?int
    {
        return $this->id_producto;
    }

    public function setIdProducto(int $id_producto): static
    {
        $this->id_producto = $id_producto;

        return $this;
    }
}

src/Entity/Pedido.php
<?php

namespace App\Entity;

use App\Repository\PedidoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
#[ORM\Entity(repositoryClass: PedidoRepository::class)]
class Pedido
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_pedido = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'id_user', referencedColumnName: 'id_user')]
    private ?User $id_user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha = null;

    #[ORM\Column]
    private ?float $total = null;


    /*  RELACIONES  */
    #[ORM\OneToMany(mappedBy: 'pedido', cascade:['persist'], targetEntity: PedidoProducto::class)]
    private Collection $pedidoProductos;

    public function __construct()
    {
        $this->pedidoProductos = new ArrayCollection();
    }

    public function getIdPedido(): ?int
    {
        return $this->id_pedido;
    }


    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(User $id_user):self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): static
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): static
    {
        $this->total = $total;

        return $this;
    }

        /**
     * @return Collection<int, PedidoProducto>
     */
    public function getPedidoProductos(): Collection
    {
        return $this->pedidoProductos;
    }

    public function addPedidoProducto(PedidoProducto $pedidoProducto): self
    {
        if (!$this->pedidoProductos->contains($pedidoProducto)) {
            $this->pedidoProductos->add($pedidoProducto);
            $pedidoProducto->setPedido($this);
        }

        return $this;
    }

    public function removePedidoProducto(PedidoProducto $pedidoProducto): self
    {
        if ($this->pedidoProductos->removeElement($pedidoProducto)) {
            // set the owning side to null (unless already changed)
            if ($pedidoProducto->getPedido() === $this) {
                $pedidoProducto->setPedido(null);
            }
        }

        return $this;
    }



}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /*  ATRIBUTOS   */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id_user = null;

    #[ORM\Column(length: 255)]
    private ?string $nombreusuario = null;

    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?int $puntos = null;

    #[ORM\Column(nullable: true)]
    private ?int $role = null;

    


    /* relaciones   */
    #[ORM\OneToOne(targetEntity: Carrito::class, mappedBy: 'id_user')]
    private  $carrito;

    public function __construct()
    {
        $this->carritos = new ArrayCollection();
    }


    /*  metodos  */
    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function getNombreusuario(): ?string
    {
        return $this->nombreusuario;
    }

    public function setNombreusuario(string $nombreusuario): static
    {
        $this->nombreusuario = $nombreusuario;

        return $this;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPuntos(): ?int
    {
        return $this->puntos;
    }

    public function setPuntos(?int $puntos): static
    {
        $this->puntos = $puntos;

        return $this;
    }

    public function getRole(): ?int
    {
        return $this->role;
    }

    public function setRole(?int $role): static
    {
        $this->role = $role;

        return $this;
    }


    
    //___________    UserInterface methods    _________________________________

    public function getUserIdentifier(): string{
        return $this->email;
    }
    public function eraseCredentials(): void{
        //$this->password = null;
    }
    public function getRoles(): array{
        /* role 0 for normal user, 1 form admins
           admins are also users */

         if($this->role==1){
            return  ["ROLE_USER"];
        }
        else if($this->role==2){
            return  ["ROLE_ADMIN"];
        }
        
        else{
        /* alternative to this: confure role hierarchy in securit.yaml*/
            return ["ROLE_USER",  "ROLE_ADMIN"];
        }
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>

        {% block body %}{% endblock %}
    </body>
</html>

templates/carrito.html.twig
{% extends 'header.html.twig' %}

{% block title %}Carrito de Compras{% endblock %}

{% block body %}
 {{ parent() }}
 <div class="carrito">
    <h1>Tu Carrito</h1>
    {% if carritoProductos is empty %}
        <p>No hay productos en tu carrito.</p>
    {% else %}
        <table>
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody >
                {% for carritoProducto in carritoProductos %}
                    <tr>
                        <td><img class="img-Producto" src="{{ carritoProducto.idProducto.img }}" alt=""></td>
                        <td >{{ carritoProducto.idProducto.name }}</td>
                        <td>{{ carritoProducto.idProducto.price }} €</td>
                        <td>
                            <div class="cart-actions">
                                <form action="{{ path('aniadirUno') }}" method="post" class="inline-form">
                                    <input type="hidden" name="idCarrito" value="{{ carrito.idCarrito }}">
                                    <input type="hidden" name="idProducto" value="{{ carritoProducto.idProducto.id_producto }}">
                                    <button type="submit">Añadir Uno</button>
                                </form>

                                <span class="quantity">{{ carritoProducto.cantidad }}</span>

                                <form action="{{ path('quitarUno') }}" method="post" class="inline-form">
                                    <input type="hidden" name="idCarrito" value="{{ carrito.idCarrito }}">
                                    <input type="hidden" name="idProducto" value="{{ carritoProducto.idProducto.id_producto }}">
                                    <button type="submit">Quitar Uno</button>
                                </form>

                                <form action="{{ path('eliminar_producto') }}" method="post" class="inline-form">
                                    <input type="hidden" name="idCarrito" value="{{ carrito.idCarrito }}">
                                    <input type="hidden" name="idProducto" value="{{ carritoProducto.idProducto.id_producto }}">
                                    <button type="submit">Eliminar</button>
                                </form>
                            </div>

                        </td>
                        <td>{{ carritoProducto.idProducto.price * carritoProducto.cantidad }} €</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="4"><h2>Total</h2></td>
                    <td><h2>{{ total }} €</h2></td>
                </tr>
            </tbody>
        </table>
    {% endif %}
</div> 
<hr>
{#<button onclick="">Realizar Compra</button>#}
<form action="{{ path('realizar_pedido') }}" method="post">
    <button type="submit">Realizar Compra</button>
</form>
<hr>

{% endblock %}

templates/compra.html.twig
{% extends 'header.html.twig' %}

{% block title %}Resumen del Pedido{% endblock %}

{% block body %}
    <div class="pedido">
    <h1>Resumen del Pedido</h1>

    <h2>Pedido #{{ pedido.idPedido }}</h2>
    <p><strong>Fecha:</strong> {{ pedido.fecha|date('d-m-Y H:i') }}</p>
    <p><strong>Precio Total:</strong> {{ pedido.total|number_format(2) }} €</p>

    <h3>Productos</h3>
    <ul>
        {% for pedidoProducto in pedidoProductos %}
            <li>
                {{ pedidoProducto.idProducto.name }} - Cantidad: {{ pedidoProducto.cantidad }} - Precio: {{ pedidoProducto.idProducto.price|number_format(2) }} €
            </li>
        {% endfor %}
    </ul>
    <div>
    <a href="{{ path('app_carrito', {'id_carrito': pedido.idUser.getIdUser()}) }}">Volver al Carrito</a>
{% endblock %}

templates/error.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Error</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8d7da;
            color: #721c24;
            text-align: center;
            padding: 50px;
        }
        .container {
            background-color: #f5c6cb;
            padding: 20px;
            border-radius: 5px;
            display: inline-block;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Error</h1>
        <p>{{ message }}</p>
        <a href="{{ path('defaults') }}">Go back to homepage</a>
    </div>
</body>
</html>

templates/header.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}MealMarket{% endblock %}</title>
        {% block stylesheets %}

        {% endblock %}

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <nav>
            
            <div class="container">
                <div class="gradient"> 
                 {% if app.user %}
                        <div>  <b>User</b>: {{ app.user.email }} 
                            <a href="{{ path('defaults') }}">Home</a> 
                            <a href="{{ path('app_perfil')}}"> Mi Perfil </a>
                            <a href="{{ path('logout') }}">Cerrar sesión</a>
                            
                        {% if carrito is defined %}  
                            <a href="{{ path('app_carrito', {'id_carrito': carrito.idCarrito}) }}" class="linkproducto">Ir al Carrito</a>
                                {% endif %}  
                        </div>
                {% else %}
                        <div>  
                            <b>User</b>: No estas logueado 
                            <a href="{{ path('defaults') }}">Home</a> 
                            <a href="{{ path('login') }}">Login</a>
                        </div>  
                {% endif %}
                            

                    <a href="{{path('defaults') }}"><img class="logo" src="..\img\logo.png"  alt="la imagen no se ha podido cargar"/></a>
                    <img class="banner" src="..\img\icono.png" alt="La img del user no se ha podido cargar" />
                </div>
            </div>
    </nav>
        {% block body %} {# BARRA DE BÚSQUEDA  #}
        <body>
        <div class="containerBusqueda">
            <div class="input-wrapper">
                <div class="icon"> <img src="img\lupa.png" alt="busqueda"/>
                    <div class="icon-inner">  </div>
                </div>
                <input type="text" class="text" placeholder="Escribe un productor para buscar...">
            </div>
            <div class="action">
                <div class="action-icon"></div>
            </div>
        </div>

        {% endblock %}
    </body>
</html>

templates/login.html.twig
{% extends 'header.html.twig' %} {# aporta el css#}

    {% block body %}

    <div style="margin-top:25 px;"  class="login-container">
            <h2>Iniciar sesión</h2>
           {#  {% if error %}
                <div class="error">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
            {% endif %}

            {#  cambiar el action  #}
            <form action="{{ path('login') }}" method="post">
                <div class="login-wrapper">
                <label style="font-weight:bolder;">Usuario</label>
                    <input type="text" name="_username" placeholder="Nombre de usuario" value="" required>
                </div>
                <div class="login-wrapper">
                <label>Contraseña</label>
                    <input type="password" name="_password" placeholder="Contraseña" required>
                </div>
                <input class="send" style="width:100%;" type="submit" value="Enviar">
                <br> <br>
                <a href="{{ path('registro') }}"> Crear una nueva cuenta</a>

            </form>
        </div>
    {% endblock %}

templates/pagPrincipal.html.twig
{% extends 'header.html.twig' %}

{% block body %}
    {{ parent() }}

    {# Ver si el usuario está logueado #}
    <div style="color:black;">
        {% if app.user %}
            <h1 style="text-align:center;">Bienvenido, {{ app.user.nombreusuario }}</h1>
        {% else %}
            <h1 style="text-align:center;">No estás autentificado.</h1>
        {% endif %}
    </div>

    {# Campo de búsqueda con botón #}
   <div style="text-align:center; margin-bottom: 20px; display: flex; justify-content: center; align-items: center;">
        <input type="text" id="search" placeholder="Buscar productos..." style="width: 50%; padding: 10px;">
        <button id="searchButton" class="searchButton" onClick="window.location.href = '{{ path("buscarProducto") }}?q=' ">Buscar</button>
    </div>

    {# Contenedor para resultados de búsqueda y todos los productos #}
    <div id="results" class="container-Productos"></div>

    {# Todos los productos #}
    <div class="container-Productos" id="product-list">
        {% if prod is defined %}
            {% for producto in prod|slice(0, 51) %}
                <div class="box-Productos">
                    <a href="{{ path('meal', {'idProduct': producto.getId_Producto()}) }}" class="linkproducto">
                        <img class="img-Producto" src="{{ producto.img }}" alt="{{ producto.name }}" />
                        <p class="TituloProd">{{ producto.name }}</p>
                        <p>Supermercado: {{ producto.supermarket }}</p>
                        <h4>{{ producto.price }} €</h4>
                    </a>
                    <form action="{{ path('addProducto', {'idProduct': producto.id_producto}) }}" method="post">
                        <input type="hidden" name="id_producto" value="{{ producto.id_producto }}">
                        <button type="submit">Agregar al Carrito</button>
                    </form>
                </div>
            {% endfor %}
        {% else %}
            <p>No se encontraron productos.</p>
        {% endif %}
    </div>

    <footer> 
        Síguenos en redes sociales: <br> <a href="https://www.instagram.com/meal_market/" target="_blank"> <img src="img\IG.png" alt="IG_logo"> </a>
    </footer>

    {% block javascript %}
    <script>
 window.onload = function() {
            console.log("JavaScript cargado y ventana completamente cargada.");

            var searchButton = document.getElementById('searchButton');
            var searchInput = document.getElementById('search');

            searchButton.addEventListener('click', function() {
                var query = searchInput.value.trim();
                console.log("Botón de búsqueda clicado. Query:", query);

                if (query.length >= 3) {
                    console.log("Redirigiendo a la búsqueda...");
                    window.location.href = '{{ path("buscarProducto") }}?q=' + encodeURIComponent(query);
                } else {
                    alert('Por favor, ingrese al menos 3 caracteres para buscar.');
                }
            });
        };

        function crearSalto(height) {
            console.log("Creando salto de línea...");
            var ele = document.createElement('div');
            ele.style.clear = 'left';
            return ele;
        }
    </script>
    {% endblock %}
{% endblock %}

templates/perfil.html.twig
{% extends "header.html.twig" %}
{% block body %} 
{{parent()}}   
<h1>Bienvenido a tu perfil {{app.user.nombreusuario}}</h1>

    <div><h2> Estos son tus pedidos anteriores: </h2>
        <table class="pedidos">
            <tr>
            <th>Id</th>
            <th>Fecha</th>
            <th>Total</th>
            </tr>
            {% for pedido in pedidos %}
                <tr> 
                <td>{{ pedido.idPedido }}</td>
                <td>{{ pedido.fecha|date("d-m-Y") }}</td>
                <td>{{ pedido.total }} €</td>
                <td><a href="{{ path('app_pedido', {'id_pedido': pedido.idPedido})}}"><button>Pedido</button></a><td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div style="margin: 5px;">
    <hr>
    <br>
    <h3> Eliminar la cuenta </h3>
    <br>


    <button onClick="if(confirm('¿Seguro que deseas eliminar tu cuenta?')) { window.location.href='{{ path('app_borrar_mi_usuario')}}'}">Eliminar Cuenta</button>

{% endblock %}

templates/productopag.html.twig
{% extends 'header.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('styles/product.css') }}">
{% endblock %}


{% block body %}


{#     {{ parent() }}
 #} <div class="containerInsideProducto">
        <img class="product-img" src="{{ producto.img }}" alt="Imagen del producto" />
        <div class="info-box">
            <div class="productInsideName">{{ producto.name }}</div>
            <div class="background-box"></div>
            <div class="priceInsideProduct">{{ producto.price }} €</div>
            <div class="ratings">Valoraciones</div>
        </div>
        <form action="{{ path('addProducto', {'idProduct': producto.id_producto}) }}" method="post" class="form-margen-izquierda">
            <input type="hidden" name="id_producto" value="{{ producto.id_producto }}">
            <button type="submit">Agregar al Carrito</button>
        </form>

    </div>

   {# ---------------------------------------------------------------------------------------------------- #}
    <div class="reviews-box">
        <form action="{{ path('opiniones') }}" method="post">
            <label for="opinion" class="EnunciadoForm">Escriba su opinión sobre el producto:</label>
            <input type="hidden" name="UsuarioIdOpiniones" value="{{  usuarioId }}">
            <input type="hidden" name="idProducto" value="{{ producto.getId_Producto() }}">
            <input type="text" id="opinion" name="opinion" required>
            <button type="submit" name="submit_opinion" class="boton-enviar">Enviar</button>
        </form>
        {#                             <form action="{{ path('aniadirUno') }}" method="post">
                                <input type="hidden" name="idCarrito" value="{{ carrito.idCarrito }}">
                                <input type="hidden" name="idProducto" value="{{ carritoProducto.idProducto.id_producto }}">
                                <button type="submit">Añadir Uno</button>
                            </form> #}
        <div  id="chat">
            {% if opiniones is not empty %}
                {% for opinion in opiniones %}
                    <div class="chat-message">
                        <strong>Author ID:</strong> {{ opinion.idUser }},
                        <strong>Message:</strong> {{ opinion.opinion }},
                    </div>
                {% endfor %}
            {% else %}
                <p class="no-messages">No hay opiniones para este articulo.</p>
            {% endif %}
        </div>
    </div> 
    {# ---------------------------------------------------------------------------------------------------- #}
    <div class="reviews-box">
        <form action="{{ path('valoraciones' ) }}" method="post">
            <label for="valoracion">Valoración:</label>
            <div class="stars">
                {% for i in 1..5 %}
                    <input type="hidden" name="UsuarioIdOpiniones" value="{{  usuarioId }}">
                    <input type="hidden" name="idProducto" value="{{ producto.getId_Producto() }}">
                    <input type="radio" id="star{{ i }}" name="valoracion" value="{{ i }}" required>
                    <label for="star{{ i }}">&#9733;</label>
                {% endfor %}
            </div>
            <button type="submit_valoracion"  class="boton-enviar">Enviar</button>
        </form>
        <div  id="chat">
            {% if valoraciones is not empty %}
                {% for valoraciones in valoraciones %}
                    <div class="chat-message">
                        <strong>Author ID:</strong> {{ valoraciones.idUser }}<br>
                        <strong>Message:</strong> {{ valoraciones.valoracion | estrellas }}
                    </div>
                {% endfor %}
            {% else %}
                <p class="no-messages">No hay valoraciones para este articulo.</p>
            {% endif %}
        </div>
    </div>

    {# ---------------------------------------------------------------------------------------------------- #}
{#         <div class="opiniones">
            {{ include('opinionesProductos.html.twig', {'opiniones': opiniones, 'idProduct':idProduct}) }}
        </div> #}
{#                  <div class="valoraciones">
            {{ include('valoracionesProductos.html.twig', {'valoraciones': valoraciones}) }}
        </div>  #}

{% endblock %}

templates/productosBuscados.html.twig
{# templates/productosBuscados.html.twig #}
{% extends 'header.html.twig' %}

{% block body %}
    {{ parent() }}



    <h1>Resultados de la búsqueda</h1>

    {% if productos is empty %}
        <p>No se encontraron productos que coincidan con tu búsqueda.</p>
    {% else %}
        <div class="container-Productos">
            {% for producto in productos %}
                <div class="box-Productos">
                    <a href="{{ path('meal', {'idProduct': producto.id_producto}) }}" class="linkproducto">
                        <img class="img-Producto" src="{{ producto.img }}" alt="{{ producto.name }}" />
                        <p class="TituloProd">{{ producto.name }}</p>
                        <p>Supermercado: {{ producto.supermarket }}</p>
                        <h4>{{ producto.price }} €</h4>
                    </a>
                    <form action="{{ path('addProducto', {'idProduct': producto.id_producto}) }}" method="post">
                        <input type="hidden" name="id_producto" value="{{ producto.id_producto }}">
                        <button type="submit">Agregar al Carrito</button>
                    </form>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

templates/registro.html.twig
{% extends 'header.html.twig' %} {# aporta el css#}
{% block body %}
{#     <header>
        <div class="container">
            <div class="gradient"></div>
            <img class="logo" src="img\logo.png"  alt="la imagen no se ha podido cargar"/>
            <img class="banner" src="img\icono.png" alt="La img del user no se ha podido cargar" />    
        </div>
    </header> 
#}
    <div class="login-container">
        <form id="registrationForm" action="{{ path('registro') }}" method="post">
            <div>
                <h1>Nuevo Usuario</h1>
                <div class="login-wrapper">
                    <label for="newEmail">Email:</label>
                    <input type="text" name="newEmail" placeholder="email@example.com"><br><br>
                    <label for="newUser">Nombre de usuario:</label>
                    <input type="text" name="newUser" placeholder="pepito"><br><br>
                    <label for="newPassword">Contraseña:</label>
                    <input type="password" id="newPassword" name="newPassword"><br><br>
                    <label for="newPassword2">Repita la contraseña:</label>
                    <input type="password" id="newPassword2" name="newPassword2"><br><br>
                </div>
                <!--Buttons Send And Clear  -->
                <input class="send" type="submit" value="Enviar"> 
                <input class="send" type="reset" value="Borrar"> <br><br>
                <a href="{{ path('login') }}"> Volver al login</a>
            </div>
        </form>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        function validatePasswords() {
            var password1 = document.getElementById("newPassword").value;
            var password2 = document.getElementById("newPassword2").value;

            if (password1 !== password2) {
                alert("Las contraseñas no coinciden.");
                return false; // Evita que el formulario se envíe
            }
            return true; // Permite que el formulario se envíe si las contraseñas coinciden
        }
    </script>
{% endblock %}